# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import frame_upload_pb2 as frame__upload__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in frame_upload_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrameUploadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadUncertainFrame = channel.stream_unary(
                '/sop.edge.v1.FrameUploadService/UploadUncertainFrame',
                request_serializer=frame__upload__pb2.FrameUploadChunk.SerializeToString,
                response_deserializer=frame__upload__pb2.UploadAck.FromString,
                _registered_method=True)


class FrameUploadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadUncertainFrame(self, request_iterator, context):
        """首条须含 metadata，其后为零条或多条 jpeg_chunk；服务端拼帧后交给注入的 handler
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameUploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadUncertainFrame': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadUncertainFrame,
                    request_deserializer=frame__upload__pb2.FrameUploadChunk.FromString,
                    response_serializer=frame__upload__pb2.UploadAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sop.edge.v1.FrameUploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sop.edge.v1.FrameUploadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrameUploadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadUncertainFrame(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sop.edge.v1.FrameUploadService/UploadUncertainFrame',
            frame__upload__pb2.FrameUploadChunk.SerializeToString,
            frame__upload__pb2.UploadAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
