# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame_upload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frame_upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66rame_upload.proto\x12\x0bsop.edge.v1\"\xd8\x01\n\x16UncertainFrameMetadata\x12\x16\n\x0eworkstation_id\x18\x01 \x01(\t\x12\x0e\n\x06sop_id\x18\x02 \x01(\t\x12\x10\n\x08sop_step\x18\x03 \x01(\x05\x12\x13\n\x0b\x63\x61ptured_at\x18\x04 \x01(\t\x12\x17\n\x0f\x65\x64ge_confidence\x18\x05 \x01(\x02\x12\x30\n\nedge_level\x18\x06 \x01(\x0e\x32\x1c.sop.edge.v1.ConfidenceLevel\x12\x16\n\tfsm_state\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_fsm_state\"i\n\x10\x46rameUploadChunk\x12\x37\n\x08metadata\x18\x01 \x01(\x0b\x32#.sop.edge.v1.UncertainFrameMetadataH\x00\x12\x14\n\njpeg_chunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04part\".\n\tUploadAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*`\n\x0f\x43onfidenceLevel\x12 \n\x1c\x43ONFIDENCE_LEVEL_UNSPECIFIED\x10\x00\x12\r\n\tCOMPLIANT\x10\x01\x12\r\n\tUNCERTAIN\x10\x02\x12\r\n\tVIOLATION\x10\x03\x32\x65\n\x12\x46rameUploadService\x12O\n\x14UploadUncertainFrame\x12\x1d.sop.edge.v1.FrameUploadChunk\x1a\x16.sop.edge.v1.UploadAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIDENCELEVEL']._serialized_start=409
  _globals['_CONFIDENCELEVEL']._serialized_end=505
  _globals['_UNCERTAINFRAMEMETADATA']._serialized_start=36
  _globals['_UNCERTAINFRAMEMETADATA']._serialized_end=252
  _globals['_FRAMEUPLOADCHUNK']._serialized_start=254
  _globals['_FRAMEUPLOADCHUNK']._serialized_end=359
  _globals['_UPLOADACK']._serialized_start=361
  _globals['_UPLOADACK']._serialized_end=407
  _globals['_FRAMEUPLOADSERVICE']._serialized_start=507
  _globals['_FRAMEUPLOADSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
